module.exports.LumpTypes = {
    Playpal: 'Playpal',
    Colormap: 'Colormap',
    Marker: 'Marker',
    MapMarker: 'Map Marker',
    MapThings: 'Map Things',
    MapLines: 'Map Lines',
    MapSides: 'Map Sides',
    MapVertices: 'Map Vertices',
    MapSegments: 'Map Segments',
    MapSubsectors: 'Map Subsectors',
    MapNodes: 'Map Nodes',
    MapSectors: 'Map Sectors',
    MapRejectTable: 'Map Reject Table',
    MapBlockmap: 'Map Blockmap',
    ANSIText: 'ANSI Text',
    Demo: 'Demo',
    TEXTUREx: 'TEXTUREx',
    PNames: 'Patch Names',
    Patch: 'Patch',
    GENMIDI: 'General MIDI Set',
    DMXGUS: 'GUS Configuration',
    SoundPC: 'Sound (PC Speaker)',
    SoundRaw: 'Sound (Raw Format)',
    MusicMUS: 'Music (MUS Format)',
    GraphicDoom: 'Graphic (Doom)',
    GraphicFlat: 'Graphic (Flat)',
    Unknown: 'Unknown'
};
module.exports.LumpTypesByName = {
    PLAYPAL: module.exports.LumpTypes.Playpal,
    COLORMAP: module.exports.LumpTypes.Colormap,
    THINGS: module.exports.LumpTypes.MapThings,
    LINEDEFS: module.exports.LumpTypes.MapLines,
    SIDEDEFS: module.exports.LumpTypes.MapSides,
    VERTEXES: module.exports.LumpTypes.MapVertices,
    SEGS: module.exports.LumpTypes.MapSegments,
    SSECTORS: module.exports.LumpTypes.MapSubsectors,
    NODES: module.exports.LumpTypes.MapNodes,
    SECTORS: module.exports.LumpTypes.MapSectors,
    REJECT: module.exports.LumpTypes.MapRejectTable,
    BLOCKMAP: module.exports.LumpTypes.MapBlockmap
};
module.exports.MapLumpTypes = [
    module.exports.LumpTypes.MapMarker,
    module.exports.LumpTypes.MapThings,
    module.exports.LumpTypes.MapLines,
    module.exports.LumpTypes.MapSides,
    module.exports.LumpTypes.MapVertices,
    module.exports.LumpTypes.MapSegments,
    module.exports.LumpTypes.MapSubsectors,
    module.exports.LumpTypes.MapNodes,
    module.exports.LumpTypes.MapSectors,
    module.exports.LumpTypes.MapRejectTable,
    module.exports.LumpTypes.MapBlockmap
];